### ISSUE TITLE
(c.Args().Get(0))

### ISSUE THREAD

**Issue by haozi4263** [wuxiaoxiaoshen/YiYi#1]
func actionBookDetail(c *cli.Context) {
	if c.NArg() == 1 {
		getBookDetail(c.Args().Get(0))
	}
}
func

请问(c.Args().Get(0))这个参数是啥意思，返回的是啥

**Comment by wuxiaoxiaoshen** [comment]
表示命令行工具接收的第一个参数，c.Args()  是一个list， 表示用户参数的集合，Get(0) 获取第一个参数，最后的效果是 ./YiYi book detail 7506337258
7506337258 表示Isbn10

**Comment by XieWeiXie** [comment]
> func actionBookDetail(c *cli.Context) {
> if c.NArg() == 1 {
> getBookDetail(c.Args().Get(0))
> }
> }
> func
> 
> 请问(c.Args().Get(0))这个参数是啥意思，返回的是啥

表示命令行工具接收的第一个参数，c.Args() 是一个list， 表示用户参数的集合，Get(0) 获取第一个参数，最后的效果是 ./YiYi book detail 7506337258
7506337258 表示Isbn10

**Comment by haozi4263** [comment]
这个参数能不能传入选项的值，
如./xkube -n im-dev get pod  将-n的值传入

**Comment by XieWeiXie** [comment]
> 这个参数能不能传入选项的值，
> 如./xkube -n im-dev get pod 将-n的值传入

可以，参考这个
  app.Flags = []cli.Flag {
    cli.StringFlag{
      Name: "lang",
      Value: "english",
      Usage: "language for the greeting",
    },
  }

  app.Action = func(c *cli.Context) error {
    name := "Nefertiti"
    if c.NArg() > 0 {
      name = c.Args().Get(0)
    }
    if c.String("lang") == "spanish" {
      fmt.Println("Hola", name)
    } else {
      fmt.Println("Hello", name)
    }
    return nil
  }

比如定义了 lang， 要获取这个值，c.String("lang")

**Comment by haozi4263** [comment]
好的，谢谢

**Comment by haozi4263** [comment]
cmd := exec.Command("/bin/bash", "-c", app)

另外：能支持windows吗?

**Comment by XieWeiXie** [comment]
> cmd := exec.Command("/bin/bash", "-c", app)
> 
> 另外：能支持windows吗?

支持的，代码逻辑不变，编译成符合windows 平台的exe 文件即可。然后example.exe -c what 之类的执行

**Comment by haozi4263** [comment]
/bin/bash", "-c"
在windows解析不了

**Comment by XieWeiXie** [comment]
> /bin/bash", "-c"
> 在windows解析不了

bash 属于unix shell, 你要执行什么，换成window cmd 啊。这不同操作系统间。要执行windows 下的 ,使用 cmd 啊

**Comment by haozi4263** [comment]
func K8s_get_pod(podname string)  {
	fmt.Printf("command run Ns:%v\n", global.Pods)

	app := `kubectl get pod -n ` + global.Ns  + "|grep "  + podname
	fmt.Printf("cmd:%v\n", app)
	cmd := exec.Command("C:/Windows/System32/cmd.exe","-c", app)
	out, _ := cmd.Output()
	fmt.Println(string(out))
}


我换成这样了不行哇

**Comment by XieWeiXie** [comment]
> func K8s_get_pod(podname string) {
> fmt.Printf("command run Ns:%v\n", global.Pods)
> 
> ```
> app := `kubectl get pod -n ` + global.Ns  + "|grep "  + podname
> fmt.Printf("cmd:%v\n", app)
> cmd := exec.Command("C:/Windows/System32/cmd.exe","-c", app)
> out, _ := cmd.Output()
> fmt.Println(string(out))
> ```
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> }
> 
> 我换成这样了不行哇

你要执行 k8s  命令是吧？cmd 是执行windows 命令哦，而且也不带 -c 参数啊。

另外，windows 下不能使用 grep 命令吧。给你个操作容器的实例吧。

func main() {
	cmd := exec.Command("docker", "images", "-a")
	out, _ := cmd.Output()
	fmt.Println(string(out))
}

kubectl 安装后，已经是可执行文件了吧。直接当成 exec.Command 的第一个参数，表示命令，后面的表示参数。

上文的容器操作命令，其实我在终端下也是这么执行的，docker images -a

所以你先试试 换成kubectl  get pods
exec.Command("kubectl", "get", "pods")

**Comment by haozi4263** [comment]
Set-Alias grep findstr grep我设置了powershell别名是没有问题的
你那种方式执行win命令是可以的，我是通过拼接变量传入的，估计win还是不行把
另外你昨天说的这个
app.Flags = []cli.Flag {
		cli.StringFlag{
			Name: "lang",
			Value: "english",
			Usage: "language for the greeting",
		},
	}

	app.Action = func(c *cli.Context) error {
		name := "Nefertiti"
		if c.NArg() > 0 {
			name = c.Args().Get(0)
		}
		if c.String("lang") == "spanish" {
			fmt.Println("Hola", name)
		} else {
			fmt.Println("Hello", name)
		}
		return nil
	}


PS E:\golang\src\github.com\gostudy\cli-14\cli_example\xkube> .\test.exe --lang spanish
PS E:\golang\src\github.com\gostudy\cli-14\cli_example\xkube>

没有执行Action

**Comment by XieWeiXie** [comment]
> Set-Alias grep findstr grep我设置了powershell别名是没有问题的
> 你那种方式执行win命令是可以的，我是通过拼接变量传入的，估计win还是不行把
> 另外你昨天说的这个
> app.Flags = []cli.Flag {
> cli.StringFlag{
> Name: "lang",
> Value: "english",
> Usage: "language for the greeting",
> },
> }
> 
> ```
> app.Action = func(c *cli.Context) error {
> 	name := "Nefertiti"
> 	if c.NArg() > 0 {
> 		name = c.Args().Get(0)
> 	}
> 	if c.String("lang") == "spanish" {
> 		fmt.Println("Hola", name)
> 	} else {
> 		fmt.Println("Hello", name)
> 	}
> 	return nil
> }
> ```
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)
> PS E:\golang\src\github.com\gostudy\cli-14\cli_example\xkube> .\test.exe --lang spanish
> PS E:\golang\src\github.com\gostudy\cli-14\cli_example\xkube>
> 
> 没有执行Action

windows 下编译成了可执行文件，应该是 test.exe --lang spanish 

我给的 ./test --lang spanish 

是因为我是linux 系统，命令没有加入环境变量，所以这样执行。

package main

import (
	"fmt"
	"log"
	"os"

	"github.com/urfave/cli"
)

func main() {
	app := cli.NewApp()

	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:  "lang",
			Value: "english",
			Usage: "language for the greeting",
		},
	}

	app.Action = func(c *cli.Context) error {
		name := "Nefertiti"
		if c.NArg() > 0 {
			name = c.Args().Get(0)
		}
		if c.String("lang") == "spanish" {
			fmt.Println("Hola", name)
		} else {
			fmt.Println("Hello", name)
		}
		return nil
	}

	err := app.Run(os.Args)
	if err != nil {
		log.Fatal(err)
	}
}


我也没做什么修改。我就复制了官网的实例。

再多说一嘴，多查看文档，多写小的实例。在说一嘴。k8s 是应用在微服务领域、云计算领域内，是不是选择Linux 系统搭建更友好啊，折腾windows 干啥。。

![image](https://user-images.githubusercontent.com/11518873/46252463-63509300-c49b-11e8-8d3c-66c56f7cee3f.png)

**Comment by haozi4263** [comment]
额 我换linux试下。k8s已经上生产了。
之前写了一个xkube shell调用kubectl用于开发人查看下载生产环境k8s日志，其他功能阉割掉
现在试试用golang写一个xkube win版本的
